"""initial 7-table schema

Revision ID: adcc4eb838ca
Revises: 
Create Date: 2026-07-05 08:48:33.941635

"""
from alembic import op
import sqlalchemy as sa


revision = 'adcc4eb838ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_credibility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('credibility_weight', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('correct_calls', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_name')
    )
    op.create_table('backtest_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('universe', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('sharpe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('calmar', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_dd', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('annual_return', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_run_id'), 'backtest_results', ['run_id'], unique=False)
    op.create_table('price_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('adjusted_close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_price_ticker_date')
    )
    op.create_index(op.f('ix_price_data_ticker'), 'price_data', ['ticker'], unique=False)
    op.create_table('research_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('note_type', sa.String(length=30), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_notes_note_type'), 'research_notes', ['note_type'], unique=False)
    op.create_index(op.f('ix_research_notes_ticker'), 'research_notes', ['ticker'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('signal_hash', sa.String(length=64), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=5), nullable=True),
    sa.Column('agent_votes', sa.JSON(), nullable=True),
    sa.Column('regime', sa.String(length=30), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=100), nullable=True),
    sa.Column('signal_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_hash')
    )
    op.create_index(op.f('ix_signals_ticker'), 'signals', ['ticker'], unique=False)
    op.create_table('system_state',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('signal_hash', sa.String(length=64), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('signal_score', sa.Integer(), nullable=True),
    sa.Column('regime', sa.String(length=30), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_hash')
    )
    op.create_index(op.f('ix_trades_ticker'), 'trades', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_ticker'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('system_state')
    op.drop_index(op.f('ix_signals_ticker'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_research_notes_ticker'), table_name='research_notes')
    op.drop_index(op.f('ix_research_notes_note_type'), table_name='research_notes')
    op.drop_table('research_notes')
    op.drop_index(op.f('ix_price_data_ticker'), table_name='price_data')
    op.drop_table('price_data')
    op.drop_index(op.f('ix_backtest_results_run_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_table('agent_credibility')
    # ### end Alembic commands ###
